export const BalanceActionTypes = {
  REQUEST_BALANCE: 'REQUEST_BALANCE',
  RECEIVE_BALANCE: 'RECEIVE_BALANCE',
  UPDATE_BALANCE: 'UPDATE_BALANCE',
  UPDATE_EXCHANGE_WAY: 'UPDATE_EXCHANGE_WAY',
} as const;
