export const CurrencyActionTypes = {
  RECEIVE_DATA: 'RECEIVE_DATA',
  REQUEST_DATA: 'REQUEST_DATA',
  SET_BASE_CURRENCY: 'SET_BASE_CURRENCY',
  GET_BASE_CURRENCY: 'GET_BASE_CURRENCY',
  SET_RECEIVE_CURRENCY: 'SET_RECEIVE_CURRENCY',
  GET_RECEIVE_CURRENCY: 'GET_RECEIVE_CURRENCY',
  UPDATE_RECEIVE_CURRENCY: 'UPDATE_RECEIVE_CURRENCY',
} as const;
